#!/bin/bash
# setup.sh — One-command installer for Nonprofit Incubator/Accelerator OS
# Usage: ./setup.sh
# Run this once after cloning the repo and filling in .env

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║     Nonprofit Incubator/Accelerator OS — Setup       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"

if [ ! -f .env ]; then
  echo -e "${RED}Error: .env not found.${NC}"
  echo "Run: cp .env.example .env  then fill in your values."
  exit 1
fi

# shellcheck source=/dev/null
source .env

for var in PAPERCLIP_API_KEY DATABASE_URL; do
  if [ -z "${!var}" ]; then
    echo -e "${RED}Error: $var not set in .env${NC}"
    exit 1
  fi
done

# Validate org config and generate org-profile.md before starting services
if [ ! -f org.config.json ]; then
  echo -e "${RED}Error: org.config.json not found.${NC}"
  echo "Fill in org.config.json with your organization details before running setup."
  exit 1
fi
python3 -c "import json; json.load(open('org.config.json'))" 2>/dev/null || {
  echo -e "${RED}Error: org.config.json is not valid JSON.${NC}"
  exit 1
}
echo "  Generating instructions/shared/org-profile.md..."
python3 - << 'PYEOF'
import json
with open('org.config.json') as f:
    cfg = json.load(f)
org = cfg['org']
inc = cfg['programs']['incubator']
acc = cfg['programs']['accelerator']
cul = cfg['culture']
lines = [
    "# Organization Profile",
    "",
    "> Auto-generated by setup.sh from org.config.json. Do not edit manually.",
    "",
    "## Who We Are",
    "**Name:** " + org['name'],
    "**Mission:** " + org['mission'],
    "**Community Served:** " + org['community_served'],
    "**Website:** " + org.get('website', ''),
    "**Contact:** " + org.get('email', ''),
    "",
    "## Our Programs",
    "",
    "### Incubator Program",
    "**Program Name:** " + inc['name'],
    "**Human Lead:** " + inc['director_name'],
    "**Contact:** " + inc['director_contact'],
    "**Serves:** " + inc['description'],
    "**Readiness Score Range:** " + str(inc['score_range'][0]) + "-" + str(inc['score_range'][1]),
    "",
    "### Accelerator Program",
    "**Program Name:** " + acc['name'],
    "**Human Lead:** " + acc['director_name'],
    "**Contact:** " + acc['director_contact'],
    "**Serves:** " + acc['description'],
    "**Readiness Score Range:** " + str(acc['score_range'][0]) + "-" + str(acc['score_range'][1]),
    "",
    "## Communication Culture",
    "**Tone:** " + cul['tone'],
    "**Primary Language:** " + cul['language_primary'],
    "**Address (male):** " + cul['address_male'],
    "**Address (female):** " + cul['address_female'],
    "**On Achievement:** " + cul['greetings']['achievement'],
    "**On Future Plans:** " + cul['greetings']['future_plans'],
    "",
    "## Routing Reference",
    "- Score 0-" + str(inc['score_range'][0] - 1) + ": Decline with constructive feedback and a path forward",
    "- Score " + str(inc['score_range'][0]) + "-" + str(inc['score_range'][1]) + ": Route to " + inc['name'] + " -- contact " + inc['director_name'] + " (" + inc['director_contact'] + ")",
    "- Score " + str(acc['score_range'][0]) + "-" + str(acc['score_range'][1]) + ": Route to " + acc['name'] + " -- contact " + acc['director_name'] + " (" + acc['director_contact'] + ")",
    "",
]
with open('instructions/shared/org-profile.md', 'w') as f:
    f.write("\n".join(lines))
print('  org-profile.md generated')
PYEOF

echo -e "${YELLOW}[1/5] Starting Docker services...${NC}"
docker compose up -d

echo -e "${YELLOW}[2/5] Waiting for services to be ready...${NC}"
for i in $(seq 1 30); do
  sleep 2
  if docker compose exec -T paperclip wget -qO- http://localhost:3100/health > /dev/null 2>&1; then
    echo "  Paperclip ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo -e "${RED}Timeout waiting for Paperclip. Check: docker compose logs paperclip${NC}"
    exit 1
  fi
  echo "  Waiting... ($((i*2))/60s)"
done

echo -e "${YELLOW}[3/5] Waiting for llama-server to load model into VRAM (~60-90s)...${NC}"
# Model file must already exist locally — run scripts/download-model.sh first.
if [ ! -f ./models/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf ]; then
  echo -e "${RED}Error: ./models/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf not found.${NC}"
  echo "Run: bash scripts/download-model.sh   (one-time, ~20GB download)"
  exit 1
fi
for i in $(seq 1 24); do   # 24 × 5s = 120s
  sleep 5
  if curl -sf http://localhost:9874/health > /dev/null 2>&1; then
    echo "  llama-server ready."
    break
  fi
  if [ "$i" -eq 24 ]; then
    echo -e "${RED}Timeout waiting for llama-server. Check: docker compose logs llm${NC}"
    exit 1
  fi
  echo "  Loading model... ($((i*5))/120s)"
done

echo -e "${YELLOW}[4/5] Applying Phase 1 database migrations...${NC}"
for f in migrations/phase1/*.sql; do
  psql "$DATABASE_URL" -f "$f" > /dev/null && echo "  ✓ $f"
done

echo -e "${YELLOW}[5/5] Creating company and Executive Director...${NC}"
bash setup/init-company.sh

echo -e "${GREEN}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║                Setup Complete! ✓                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo "  Paperclip dashboard:  http://localhost:3100"
echo "  Staff UI:             http://localhost:80"
echo ""
echo "Next steps:"
echo "  1. Open Paperclip and approve the Executive Director strategy"
echo "  2. Approve director hire requests as they appear"
echo "  3. Open Staff UI → DataEntry to seed initial data (mentors, compliance items, etc.)"
echo "  4. Your org builds itself from here"
echo ""
echo "Phase 2 when ready:  bash scripts/activate-phase.sh 2"
echo "n8n bridge:          docker compose -f docker-compose.yml -f docker-compose.n8n.yml up -d"
