#!/usr/bin/env python3
"""
generate-org-profile.py
Reads org.config.json and writes instructions/shared/org-profile.md.
Called by setup.sh before docker compose up.
"""
import json
import sys
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    with open(os.path.join(root, 'org.config.json')) as f:
        cfg = json.load(f)
except FileNotFoundError:
    print('ERROR: org.config.json not found. Fill it in before running setup.sh.')
    sys.exit(1)
except json.JSONDecodeError as e:
    print(f'ERROR: org.config.json is not valid JSON: {e}')
    sys.exit(1)

org = cfg['org']
inc = cfg['programs']['incubator']
acc = cfg['programs']['accelerator']
cul = cfg['culture']

lines = [
    '# Organization Profile',
    '',
    '> Auto-generated by setup.sh from org.config.json. Do not edit manually.',
    '> To update, edit org.config.json and re-run ./setup.sh.',
    '',
    '## Who We Are',
    '**Name:** ' + org['name'],
    '**Mission:** ' + org['mission'],
    '**Community Served:** ' + org['community_served'],
    '**Website:** ' + org.get('website', ''),
    '**Contact:** ' + org.get('email', ''),
    '',
    '## Our Programs',
    '',
    '### Incubator Program',
    '**Program Name:** ' + inc['name'],
    '**Human Lead:** ' + inc['director_name'],
    '**Contact:** ' + inc['director_contact'],
    '**Serves:** ' + inc['description'],
    '**Readiness Score Range:** ' + str(inc['score_range'][0]) + '-' + str(inc['score_range'][1]),
    '',
    '### Accelerator Program',
    '**Program Name:** ' + acc['name'],
    '**Human Lead:** ' + acc['director_name'],
    '**Contact:** ' + acc['director_contact'],
    '**Serves:** ' + acc['description'],
    '**Readiness Score Range:** ' + str(acc['score_range'][0]) + '-' + str(acc['score_range'][1]),
    '',
    '## Communication Culture',
    '**Tone:** ' + cul['tone'],
    '**Primary Language:** ' + cul['language_primary'],
    '**Address (male):** ' + cul['address_male'],
    '**Address (female):** ' + cul['address_female'],
    '**On Achievement:** ' + cul['greetings']['achievement'],
    '**On Future Plans:** ' + cul['greetings']['future_plans'],
    '',
    '## Routing Reference',
    '- Score 0-' + str(inc['score_range'][0] - 1) + ': Decline with constructive feedback and a path forward',
    '- Score ' + str(inc['score_range'][0]) + '-' + str(inc['score_range'][1]) + ': Route to ' + inc['name'] + ' -- contact ' + inc['director_name'] + ' (' + inc['director_contact'] + ')',
    '- Score ' + str(acc['score_range'][0]) + '-' + str(acc['score_range'][1]) + ': Route to ' + acc['name'] + ' -- contact ' + acc['director_name'] + ' (' + acc['director_contact'] + ')',
    '',
]

out_path = os.path.join(root, 'instructions', 'shared', 'org-profile.md')
with open(out_path, 'w') as f:
    f.write('\n'.join(lines))

print('  org-profile.md generated from org.config.json')
